### ISSUE TITLE
talisker should be explicit about it's dependency on celery >= 3.1.0

### ISSUE THREAD

**Issue by ricardokirkner** [canonical-ols/talisker#20]
The minimum supported version of celery (3.1.0) is only listed in the requirements.devel file. This should really be specified in setup.py as it's a run-time minimum version requirement as well.

**Comment by bloodearnest** [comment]
Well, it's an optional dependency, and it may work with older versions, I will check.

So the best we can do I think is to add a setuptools extra block, so we can pip install talisker[celery]?

At least I can't immediately see another route?

I'll look into it, but as it's optional it's difficult to guarantee it, as the user may install celery any which way rather than via talisker[celery]. We could perhaps do a version check in code at celery import time?

We should document it in the celery docs page, for sure.

**Comment by bloodearnest** [comment]
See https://github.com/canonical-ols/talisker/pull/25/

**Comment by bloodearnest** [comment]
Fixed in 8f85106240261d1219680b065e729eaab90078ca
