### ISSUE TITLE
Should Talisker define a "gevent" extra?

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/talisker#491]
Talisker offers `talisker.gunicorn.gevent`, but AFAIK it only works if you have gevent installed locally yourself. Talisker doesn't mention it as a dependencies.

Shouldn't we be able to install `talisker[gevent]` to bring down the version of gevent that Talisker needs?

**Comment by bloodearnest** [comment]
If you plan on using gunicorn with gevent, you should explicitly install gunicorn[gevent], as well as talisker[gunicorn], IMO.  Talisker needs whatever version of gevent the version of gunicorn you're using needs. Talisker doesn't require gunicorn anymore, so that's a dependency decision for the project to make. Essentially, support for gevent is deferred to gunicorn. If talisker supports that version of gunicorn, it supports the versions of gevent that that version of gunicorn supports.

Ideally, we wouldn't make talisker.gunicorn.gevent available if you don't have gevent or even gunicorn installed, but we cannot. You might install them *after* installing talisker, and there's no way to add new entrypoints post install that I know of. So the best bet is to install the entrypoint, and have it warn if gunicorn and gevent are not installed.

Also, that entrypoint is a minor workaround for https://github.com/psf/requests/issues/3752 so only needed if you're a) using python3.6 b) using requests to talk to https backends, as opposed to a first class entrypoint.  So it will hopefully disappear in the future, when that bug is fixed.

**Comment by nottrobin** [comment]
We include gunicorn with `talisker[gunicorn]`. Is that wrong? Since we're doing that, it seems to me that it would make sense for us to do `talisker[gunicorn,gevent]`. This allows talisker to choose a version of gunicorn that it knows is compatible.

Are you saying we should change this to:

```
gunicorn[gevent]==x.x.x
talisker==x.x.x
```

Because I'm worried that as new versions of gunicorn / talisker are released we risk the two ending up on incompatible versions.

**Comment by bloodearnest** [comment]
> We include gunicorn with `talisker[gunicorn]`. Is that wrong? Since we're doing that, it seems to me that it would make sense for us to do `talisker[gunicorn,gevent]`, or perhaps `talisker[gunicorn-gevent]`. This allows talisker to choose a version of gunicorn that it knows is compatible.

I do not recommend doing this, as pulling in new versions of talisker will pull in new versions of gunicorn. IMO you should explicitly pin gunicorn and gevent, as they are vital operational dependencies.
 
> 
> Are you saying we should change this to:
> 
> ```
> gunicorn[gevent]==x.x.x
> talisker==x.x.x
> ```
> 
> Because I'm worried that as new versions of gunicorn / talisker are released we risk the two ending up on incompatible versions.

I would do this:

gevent==foo
gunicorn[gevent]==bar
talisker[gunicorn]==baz

This is explicit but also gives the tooling chance to detect version incompatibilities, as the extras bring in additional constraints on your pinned version. But you should still pin your version.

Note: I just tested the above with gunicorn 20.0.0, which talisker[gunicorn] explicitly doesn't support, and no issue was detected, so it's possible that talisker's packaging metadata is bugged, or that pip doesn't detect the clash properly. I'll look into the former, but if it's the latter, then what your asking for will not help anyway.

Anyway, Talisker will not add explicit extras for dependencies of dependencies.  It's too much maintenance work, and adds little value. Talisker supports such a broad range of libraries that the testing matrix is already large and brittle enough. We can't test for everything.

**Comment by nottrobin** [comment]
> Anyway, Talisker will not add explicit extras for dependencies of dependencies. It's too much maintenance work, and adds little value. Talisker supports such a broad range of libraries that the testing matrix is already large and brittle enough. We can't test for everything.

That's fair enough. That being the case, I'll do it the way you suggest.

Having made that determination, this is now purely an academic discussion, but I don't follow your general attitude here:

> I do not recommend doing this, as pulling in new versions of talisker will pull in new versions of gunicorn.

Updating Talisker to update Gunicorn is absolutely what I'd expect. From our perspective, Talisker is our WSGI server. We have no dependency on Gunicorn that isn't through Talisker, and of course we shouldn't be expected to know which Gunicorn interface Talisker expects.

> IMO you should explicitly pin gunicorn and gevent, as they are vital operational dependencies.

I don't see how Gunicorn and gevent, which for our purposes here are sub-dependencies, are different from any other such dependency.

We actually explicitly pin everything, including Talisker, and then we use Renovate to propose PRs to update dependencies - meaning we would test the update at that point, with any new sub-dependencies that have been updated.

**Comment by bloodearnest** [comment]
> > Anyway, Talisker will not add explicit extras for dependencies of dependencies. It's too much maintenance work, and adds little value. Talisker supports such a broad range of libraries that the testing matrix is already large and brittle enough. We can't test for everything.
> 
> That's fair enough. That being the case, I'll do it the way you suggest.
> 
> Having made that determination, this is now purely an academic discussion, but I don't follow logic here:
> 
> > I do not recommend doing this, as pulling in new versions of talisker will pull in new versions of gunicorn.
> 
> Updating Talisker to update Gunicorn is absolutely what I'd expect. From our perspective, Talisker is our WSGI server. 

That perspective is not correct. Talisker is not a WSGI server. Gunicorn is. Talisker is merely a wrapper round gunicorn invocation that configures it a certain way (logging, defaults, and default middleware). Gunicorn is your WSGI server, not Talisker.

Talisker does the same thing with twistd as WSGI server in landscape, for example. And there are vague plans for uwsgi support too.

> We have no dependency on Gunicorn that isn't through Talisker, 

The talisker[gunicorn] extra allows you do this, sure. I think it is bad practice, as you should be explicit about changing dependencies as key as your WSGI server. But it's one approach.

> and of course we shouldn't be expected to know which Gunicorn interface Talisker expects.

Indeed - that's the whole point of the gunicorn extra in Talisker - it explicitly documents the *range* of versions Talisker is tested with. Good dependency tooling *should* be able to detect any clash automatically. 

> > IMO you should explicitly pin gunicorn and gevent, as they are vital operational dependencies.
> 
> I don't see how Gunicorn and gevent, which for our purposes here are sub-dependencies, are different from any other such dependency.

Gunicorn is direct dependency of Talisker. Gevent is an optional dependency of gunicorn, not of Talisker directly. 

> We actually explicitly pin everything, including Talisker, and then we use Renovate to propose PRs to update dependencies - meaning we would test the update at that point, with any new sub-dependencies that have been updated.

Yes, this is good. But is completely orthogonal to the original issue question.

You should use gunicorn[gevent] to ensure that the version of gevent you are using works with the version of gunicorn you are using.

Likewise, you should use talisker[gunicorn] to ensure that the version of gunicorn you are using works with the version of talisker you are using.

Talisker is coupled to gunicorn, not gevent, essentially*.

In either case, you can choose to explicitly pin the sub-dependency (gevent and gunicorn, respectively), but you don't have to. I would argue it's better practice to explicitly pin (and indeed that's what poetry does), especially for such key operational dependencies as gunicorn and gevent. I've had so many weird production issues with gevent over the years (although it's better these days) that I want to be in control of explicit control of reving it's version. YMMV.

*For correctness, there are two places talisker imports gevent directly. In the per-request context (we use gevent.local in one place, because we have to), and in the above talisker.gunicorn.gevent, which is a temporary workaround. Given that gevent.local() actually an implementation of threading.local() API, it is by definition b/w compatible. So I don't feel that that warrants the extra maintenance of an explicit dependency.
