### ISSUE TITLE
Talisker breaks ipdb for gunicorn gevent

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/talisker#529]
Most people in my team use [ipdb](https://pypi.org/project/ipdb/) quite heavily for debugging our websites.

A month or so ago we noticed that `ipdb` has stopped working, raising a "TypeError: 'type' object is not subscriptable" error that was hard to track down.

I did a little investigation(1) last night (with @jkfran's help) and it turns out that this error only appears when using gevent workers, and it appears in gunicorn only after Talisker is installed. So I guess Talisker is doing some monkey-patching of something low-level that causes this issue.

Would you be able to shed some more light on this error?

1: https://github.com/nottrobin/gunicorn-ipdb-error

**Comment by nottrobin** [comment]
Sorry, I might as well write the steps to reproduce inline here:

``` bash
python3 -m venv .venv
source .venv/bin/activate
pip3 install --upgrade pip  # gevent might needs a newer pip version
pip3 install gevent gunicorn ipdb  # Don't install Talisker yet
wget https://raw.githubusercontent.com/nottrobin/gunicorn-ipdb-error/master/wsgi.py  # A "hello world" WSGI script
gunicorn wsgi:application --worker-class gevent
```

In another terminal, do `curl localhost:8000`, see the debugger run fine. Quit the debugger and the server. Then:

``` bash
pip3 install talisker
gunicorn wsgi:application --worker-class gevent
```

Now `curl localhost:8000`, see the error in the server:

```
...
  File "/home/robin/Projects/gunicorn-ipdb-error/.venv/lib/python3.6/site-packages/prompt_toolkit/application/current.py", line 70, in <module>
    "_current_app_session", default=AppSession()
TypeError: 'type' object is not subscriptable
```

**Comment by jkfran** [comment]
The issue doesn't occur in Python 3.7 or greater. Looks like there is an issue with contextvars and Python 3.6.

**Comment by bloodearnest** [comment]
Hi, just saw this today.

So this is not an issue with Talisker, but an issue with one of ipdb dependencies (prompt_toolkit) internal usage of ContextVar with typing, and gevent's contextvar support, on py3.6. It's only triggered when the contextvars backport package is installed, which is why installing Talisker on py36 triggers it. When there's no contextvars import, prompt_toolkit fallsback to a dummy implementation that avoids the issue [because it's explicitly typed in the class declaration](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/prompt_toolkit/eventloop/dummy_contextvars.py#L26).

prompt_toolkit uses a ContextVar like so:

    #.venv/lib/python3.6/site-packages/prompt_toolkit/application/current.py:70
    _current_app_session: ContextVar["AppSession"] = ContextVar(
        "_current_app_session", default=AppSession()
    )

At this point, ContextVar is actually gevent.contextvars.ContextVar, as gevent has monkeypatched it. And this includes a typing declaration. However, gevent's ContextVar doesn't use typing in its declaration, and instead [relies on `__class_getitem__`](https://github.com/gevent/gevent/blob/master/src/gevent/contextvars.py#L130) for typing support.  However, this was only added from python 3.7+, with the [introduction of `__class_getitem__`](https://docs.python.org/3/whatsnew/3.7.html#pep-560-core-support-for-typing-module-and-generic-types). 

So, on python3.6, the interpreter doesn't parse this properly, and instead tries to call `__getitem__` on gevent.contextvar.ContextVar, which raises as we see. On py37+, the interpreter correctly calls `__class_getitem__`, which is supported and works as intended.

This is all confirmed by the fact that if I remove the typing declaration in ipdb, everything works fine in python3.6.

So possible fixes include removing the typing from prompt_toolkit, or switching gevent's ContextVar implementation to be inherited from typing.Generic[T], so it supports the usage.

So, this an gevent/prompt_toolkit compatibility issue, rather than a talisker one per se.

**Comment by nottrobin** [comment]
Thanks for the thorough explanation @bloodearnest. As long as we know it works with python 3.7+ we're fine, we'll just update everything to that.
