### ISSUE TITLE
talisker > 0.6.7 does not work with celery 3.1.23

### ISSUE THREAD

**Issue by thomir** [canonical-ols/talisker#59]
We had deployed delta-service with talisker 0.6.7 and celery 3.1.23. This combination was working fine. Upon upgrading to talisker 0.9.0, we can now no longer queue tasks:

https://sentry.ols.staging.canonical.com/canonical/delta-service/issues/43/

The version of celery has not changed. Downgrading talisker to 0.6.7 fixes the problem. I realise this is super odd - the stack trace is entirely inside celery itself... but perhaps talisker patches some aspect of celery?

I downgraded talisker on stg, and verified that everything started working again. Then upgraded again, and verified that it broke again. The only package that changed was talisker. 

celery 4.0 is out now, but the talisker docs do not mention whether 4.x is supported - I'm n ot sure if upgrading celery *and* talisker will help (and I wanted to avoid too many simultaneously moving parts).

**Comment by bloodearnest** [comment]
Hey, 

So, I accidentally added a dependency on a celery 4.0+ function signature that I didn't need to, apologies.

I do have some tests I run to check against the lower bound of supported package versions, but they didn't catch it as it required an actual broker to detect the failure, as my unit tests just called the signal handlers directly, rather than get celery machinery to invoke them.

I have a WIP branch that a) fixes the issue and b) changes the unit tests to use an in-memory celery broker in a different thread for functional testing.
