### ISSUE TITLE
Requests error during ssl with eventlet

### ISSUE THREAD

**Issue by j-walker23** [canonical-ols/talisker#98]
Hey, thanks for your help with my previous noob question with PyCharm and debugging. Your link totally worked. Funny i didn't know about that before because i have never been able to dev in the same env as prod. Which is why i have been so excited about `talisker`. Hopefully will finally catch some prod env bugs before deployment.

I pretty much got my entire setup refactored to using `talisker` which was awesome and started testing some things. There seems to be an error when making any external https requests. This time i have a small test case for you, i just hope it isn't `macOS` related. The error isn't surfaced so i don't have that.

Command is `talisker -k eventlet taltest:app`.
Changing to `gunicorn -k eventlet taltest:app` does not error so i hoped you would know how to surface the error and then it would be an easy fix.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Talisker repro with ssl and requests on py 3.6

eventlet==0.21.0
Flask==0.12.2
talisker==0.9.5
"""

from flask import Flask
app = Flask(__name__)

import requests
print(requests.get("https://google.com"))
```

One weird thing is i changed `talisker.gunicorn.run` to below just to play with things. And the error didn't go away. Which stumped me since i copied the lines from the `gunicorn.wsgiapp.run` method.

```
def run():
  # config = talisker.initialise()
  # talisker.celery.enable_signals()
  # return TaliskerApplication(
  #     "%(prog)s [OPTIONS] [APP_MODULE]", config['devel'], config['debuglog'])
  from gunicorn.app.wsgiapp import WSGIApplication
  return WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
```

**Comment by j-walker23** [comment]
I am not 100% yet but i think one of my problems might be fixed with monkey patching.

If i add below to the top of `talisker/gunicorn.py` then the ssl error goes away. Is there anyway right now in talisker i could run the below before talisker ever imports the requests module?

```
import eventlet
eventlet.monkey_patch()
```

**Comment by bloodearnest** [comment]
Right, as you say, you need to monkeypatch, or use async aware apis/tools (e.g. like https://github.com/saghul/erequests or https://github.com/kennethreitz/grequests).

Gunicorn actually enables monkeypatching for you, see:

https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/geventlet.py#L90
https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/ggevent.py#L57

Interestingly, your test app works fine for me in py 3.5, but not in py 3.6, which is very odd. But looking around, I see this issue has been encountered:

https://github.com/requests/requests/issues/3752
https://github.com/gevent/gevent/issues/903
https://github.com/eventlet/eventlet/issues/371 (you seem to have commented on this one! :)

So, my reading of this is that, on python 3.6, requests has to be imported *after* monkey patching, to workaround this bug. At least until some later version of requests. I tested with 2.17.3, and the bug is still present.

So, this is a bit tricky to solve, as talisker imports requests early. I think we may need to rework talisker's requests integration to lazily import requests, rather than when talisker.requests is imported. I will take a stab it ASAP.

**Comment by j-walker23** [comment]
Really appreciate it, thanks again for your help.

**Comment by bloodearnest** [comment]
Pushed a branch that provides a workaround, if you'd like to take a look. I think that's all we can do in this scenario.

On a philosophical note, this is a good example of the downside of vendoring dependencies, in this case requests and urllib3. Probably still worth it on balance.

**Comment by j-walker23** [comment]
Nice! Thanks, i will check it out. 

I understand about the vendor deps. I personally feel like it makes sense in this repo. But i would be bias since i use all the major ones already. It's named `talisker` for a reason : ). And for the last year i have been rolling my own version for a lot of these helpers/practices and there has never been a day where i felt good about any of it holistically. 

Now having something to rely on for overall app startup thats much more sophisticated then any roll my own guesswork is really exciting. Plus i learned some cool tricks i wasn't aware of.

**Comment by bloodearnest** [comment]
On 31 May 2017 11:01 pm, "John Walker" <notifications@github.com> wrote:

Nice! Thanks, i will check it out.

I understand about the vendor deps. I personally feel like it makes sense
in this repo. But i would be bias since i use all the major ones already.

Hah, sorry, that was ambiguously worded by me. I was referring to requests
vendoring urllib3. Talisker currently doesn't vendor anything.

It's named talisker for a reason : ). And for the last year i have been
rolling my own version for a lot of these helpers/practices and there has
never been a day where i felt good about any of it holistically.


Yeah, that was one of the goals. Move our copypasta glue code into single
codebase, that's well tested and released properly. Glad you appreciate the
benefits of that :)

Now having something to rely on for overall app startup thats much more
sophisticated then any roll my own guesswork is really exciting. Plus i
learned some cool tricks i wasn't aware of.

\o/

-- 
Simon

**Comment by bloodearnest** [comment]
Good grief, made the mistake of replying by email, sorry!

**Comment by j-walker23** [comment]
Haha, np.

Yeah, i totally thought you were talking about your dependencies. Makes sense now. I have always seen all of the sub packaged deps in `requests` but never actually read up on why. Are they just helpers for py 2-3 issues or whats the point?

**Comment by bloodearnest** [comment]
I believe it's for stability and control for the requests maintainers, and a good user experience for most users. It makes sense, it's a trade off. One downside is that you cannot upgrade a dependency independently, e.g. to use a version of urllib3 that fixes this issue.

**Comment by j-walker23** [comment]
Oh man, just coming up from a rabbit hole. Right off the bat changing to the new entry point didn't work. But all of the code looked good and gunicorn just restarts when it errors out and doesn't show the error. Or at least for this problem it doesn't.

So after commenting/uncommenting throughout the entire lib trying to figure what was causing this i finally get a hit.

`talisker.statsd`
```python
from urllib.parse import urlparse, parse_qs
# from future.moves.urllib.parse import urlparse, parse_qs
```

First main question is when it errors, gunicorn just restarts itself and doesn't display anything. Do you know how to prevent that? I know its not related to `talisker`, just curious. I can't find a way.

I know that change would only work for py3 so i know its not a fix. But i hoped it would help anyway.
Is the `future` package just a 2-3 helper so this should work anyway?

**Comment by j-walker23** [comment]
Hey, you can actually ignore this. I am working some consulting with another guy and that is the project i was excited about since it used the same techs. But my co-worker just informed me about the GNU Public License and it not being allowed on private repos. I sadly didn't even think about looking first, something need to get better at. And even more sadly the owner would not go for making it OSS.

Anyway, thanks again for the help!
